title: Matt Anderson
#logo: /assets/img/profile.png
description: >
  Information security specialist, 
  GRC Consultant and project manager with 15 years’ experience leading IT transformation programs across many industry verticals.
  <br><br>
  <a href="https://phishbate.com">Blog</a> 
#show_downloads: true
theme: jekyll-theme-minimal
google_analytics: G-0P1TB7SS5Y
